version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.4.0-browsers
    steps:
      - checkout
      - restore_cache:
        keys: v1-dependencies-{{ checksum "package.json" }}
      - run:
        name: Install Dependencies
        command: npm install
      - run:
        name: Linting
        command: npm run lint
      - run:
        name: Building
        command: npm run build --prod
      - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - dist
          - package.json
          - firebase.json
          - .firebaserc
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.4.0-browsers
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Firebase
          command: npm install --save-dev firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: npm run firebase-deploy

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
                only: master
